# Generated by Django 5.2.14 on 2026-05-18 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helmet_id', models.CharField(max_length=20, unique=True)),
                ('battery', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('safe', 'Safe'), ('accident', 'Accident Detected'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('gps_active', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('rider', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='riders.rider')),
            ],
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_description', models.CharField(default='Unknown', max_length=200)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('helmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='accidents.helmet')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceleration', models.FloatField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('tilt', models.FloatField(default=0.0)),
                ('helmet_worn', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('helmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='accidents.helmet')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
